services:
  - type: web
    name: fastapi-playwright-render
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
